# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ControleVencimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('venciemnto', models.DateField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=50)),
                ('certidao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dose', models.IntegerField(default=0)),
                ('cartao', models.ManyToManyField(through='vacpass.ControleVencimento', to='vacpass.Cartao')),
            ],
        ),
        migrations.AddField(
            model_name='dependente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Usuario'),
        ),
        migrations.AddField(
            model_name='controlevencimento',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Vacina'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='dependente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Dependente'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Usuario'),
        ),
    ]
