# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ControleVencimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('vencimento', models.DateField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Cartao')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=50)),
                ('certidao', models.CharField(max_length=50)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Cartao')),
            ],
        ),
        migrations.CreateModel(
            name='doseVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.IntegerField()),
                ('duracaoMeses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Cartao')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cartao', models.ManyToManyField(through='vacpass.ControleVencimento', to='vacpass.Cartao')),
            ],
        ),
        migrations.AddField(
            model_name='dosevacina',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Vacina'),
        ),
        migrations.AddField(
            model_name='dependente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Usuario'),
        ),
        migrations.AddField(
            model_name='controlevencimento',
            name='vacina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.Vacina'),
        ),
    ]
