# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0002_remove_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='CPF',
            field=models.CharField(max_length=15),
        ),
    ]
