# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0003_auto_20170406_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependente',
            old_name='certidao',
            new_name='ndocumento',
        ),
        migrations.RemoveField(
            model_name='dependente',
            name='CPF',
        ),
        migrations.AddField(
            model_name='dependente',
            name='tipo',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('certidao', 'certidao')], default=12, max_length=10),
            preserve_default=False,
        ),
    ]
