# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0003_auto_20170406_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='disponibilidade',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vacina',
            name='funcionalidade',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vacina',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vacina',
            name='proibitivos',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='vacina',
            name='publico_alvo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
