# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0004_auto_20170412_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosevacina',
            old_name='duracaoMeses',
            new_name='idade',
        ),
    ]
