# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0005_auto_20170412_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosevacina',
            name='idade',
            field=models.CharField(max_length=50),
        ),
    ]
