# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0006_auto_20170412_1519'),
        ('vacpass', '0004_auto_20170410_1018'),
    ]

    operations = [
    ]
