# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0009_auto_20170531_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevencimento',
            name='avisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controlevencimento',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.DoseVacina'),
        ),
    ]
