# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0012_auto_20170609_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Resolvido')], default=1),
        ),
        migrations.AlterField(
            model_name='controlevencimento',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.DoseVacina'),
        ),
    ]
