# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0013_auto_20170609_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='status',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='controlevencimento',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.DoseVacina'),
        ),
    ]
