# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0016_auto_20170611_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='recomendacao',
        ),
        migrations.AlterField(
            model_name='controlevencimento',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.DoseVacina'),
        ),
    ]
