# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacpass', '0017_auto_20170611_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlevencimento',
            name='dose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacpass.DoseVacina'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'CPF'), (2, 'RG'), (3, 'certidao')]),
        ),
    ]
